// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXe5L3ouvGiUfYMXOknIW6UuLsgQXy7Vg',
    appId: '1:462344527849:web:4b4221d858eb7426fc3578',
    messagingSenderId: '462344527849',
    projectId: 'mynotes-bf501',
    authDomain: 'mynotes-bf501.firebaseapp.com',
    databaseURL: 'https://mynotes-bf501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-bf501.appspot.com',
    measurementId: 'G-BYMBLX6994',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYN7ZBAt6hJr-ohv6b2JKoaxoJugvoC4E',
    appId: '1:462344527849:android:620877191b27f236fc3578',
    messagingSenderId: '462344527849',
    projectId: 'mynotes-bf501',
    databaseURL: 'https://mynotes-bf501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-bf501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr9p8VOI0vA5jB5bXgLbA0F3mi_IWsboU',
    appId: '1:462344527849:ios:054806f2fe535bb0fc3578',
    messagingSenderId: '462344527849',
    projectId: 'mynotes-bf501',
    databaseURL: 'https://mynotes-bf501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-bf501.appspot.com',
    iosBundleId: 'com.personaljw.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr9p8VOI0vA5jB5bXgLbA0F3mi_IWsboU',
    appId: '1:462344527849:ios:054806f2fe535bb0fc3578',
    messagingSenderId: '462344527849',
    projectId: 'mynotes-bf501',
    databaseURL: 'https://mynotes-bf501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-bf501.appspot.com',
    iosBundleId: 'com.personaljw.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXe5L3ouvGiUfYMXOknIW6UuLsgQXy7Vg',
    appId: '1:462344527849:web:742d5b3366639f29fc3578',
    messagingSenderId: '462344527849',
    projectId: 'mynotes-bf501',
    authDomain: 'mynotes-bf501.firebaseapp.com',
    databaseURL: 'https://mynotes-bf501-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynotes-bf501.appspot.com',
    measurementId: 'G-5FNL503NBF',
  );
}
